name: bedtools_genomecov
description: Computes per-base genome coverage from a BAM file and filters regions
  below a coverage threshold
keywords:
  - bed
  - bam
  - genomecov
  - bedtools
  - coverage
tools:
  - bedtools:
      description: |
        A set of tools for genomic analysis tasks, specifically enabling genome
        arithmetic (merge, count, complement) on various file types.
      homepage: https://bedtools.readthedocs.io/
      documentation: https://bedtools.readthedocs.io/en/latest/content/tools/genomecov.html
      licence: ["MIT"]
      identifier: biotools:bedtools
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - intervals:
        type: file
        description: BAM file to compute coverage from
        pattern: "*.{bam}"
        ontologies: []
    - scale:
        type: integer
        description: |
          Scale factor for the output. Set to 1 to disable. Setting to a value
          other than 1 will also enable -bg bedgraph output format.
output:
  genomecov:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.bed":
          type: file
          description: BED file of regions below the coverage threshold
          pattern: "*.bed"
          ontologies: []
  versions_bedtools:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - bedtools:
          type: string
          description: The tool name
      - "bedtools --version | sed -e 's/bedtools v//g'":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - bedtools:
          type: string
          description: The tool name
      - "bedtools --version | sed -e 's/bedtools v//g'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@edmundmiller"
  - "@sruthipsuresh"
  - "@drpatelh"
  - "@sidorov-si"
  - "@chris-cheshire"
maintainers:
  - "@edmundmiller"
  - "@sruthipsuresh"
  - "@drpatelh"
  - "@sidorov-si"
  - "@chris-cheshire"
