name: seqtk_parse
description: Creates a summary of mapping statistics for a set of samples based on
  the output from seqtk
keywords:
  - mapping
  - statistics
  - summary
  - seqtk
tools:
  - python:
      description: |
        Python is a programming language that lets you work quickly and integrate
        systems more effectively.
      homepage: https://www.python.org/
      documentation: https://docs.python.org/3/
      licence: ["PSF-2.0"]
      identifier: ""
  - pandas:
      description: |
        pandas is a fast, powerful, flexible and easy to use open source data
        analysis and manipulation tool built on top of Python.
      homepage: https://pandas.pydata.org/
      documentation: https://pandas.pydata.org/docs/
      licence: ["BSD-3-Clause"]
      identifier: ""
input:
  - - tsv:
        type: file
        description: |
          Per-sample mapping statistics TSV files from seqtk comp
        pattern: "*.tsv"
        ontologies: []
output:
  tsv:
    - - "mapping_summary.tsv":
          type: file
          description: Summary of mapping statistics for all samples in TSV format
          pattern: "*.tsv"
          ontologies: []
  versions_seqtk_parse:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - python:
          type: string
          description: The tool name
      - "python --version | sed 's/Python //g'":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - python:
          type: string
          description: The tool name
      - "python --version | sed 's/Python //g'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@avantonder"
maintainers:
  - "@avantonder"
