name: fastq_scan_parse
description: Creates a summary of FASTQ quality statistics for a set of samples based on the output from fastq-scan
keywords:
  - FASTQ
  - quality
  - statistics
input:
  - - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
    - json:
        type: file
        description: |
          The input channel containing the fastq-scan output files in JSON format
        pattern: "*.fa"
output:
  tsv:
    type: file
    description: |
      Summary of FASTQ quality statistics for the samples in TSV format
    pattern: "*.tsv"
  versions_fastq_scan_parse:
    - - ${task.process}:
          type: string
          description: The name of the process
      - fastq_scan_parse:
          type: string
          description: The name of the tool
      - "python --version | sed 's/Python //g'":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - fastq_scan_parse:
          type: string
          description: The name of the tool
      - "python --version | sed 's/Python //g'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@avantonder"
maintainers:
  - "@avantonder"
