name: get_genome_size
description: Extracts the total genome size from SAMtools faidx output
keywords:
  - fasta
  - genome
  - size
  - awk
tools:
  - gawk:
      description: |
        GNU awk is a pattern scanning and processing language useful for
        data extraction and reporting.
      homepage: https://www.gnu.org/software/gawk/
      documentation: https://www.gnu.org/software/gawk/manual/
      licence: ["GPL-3.0-or-later"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'reference' ]
    - size_file:
        type: file
        description: |
          File containing the output from SAMtools faidx (.sizes file)
        pattern: "*.sizes"
        ontologies: []
output:
  ch_genome_size:
    - - genome_size:
          type: string
          description: Total genome size calculated from the faidx sizes file
  versions_get_genome_size:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - gawk:
          type: string
          description: The tool name
      - "$awk -version | sed '1!d; s/.*awk version//; s/,.*//'":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - gawk:
          type: string
          description: The tool name
      - "$awk -version | sed '1!d; s/.*awk version//; s/,.*//'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@project-defiant"
maintainers:
  - "@avantonder"
