name: alignpseudogenomes
description: Creates a multiple sequence alignment of pseudogenomes for a set of samples
keywords:
  - pseudogenome
  - MSA
  - reference
  - alignment
tools:
  - biopython:
      description: |
        Biopython is a set of freely available tools for biological computation
        written in Python.
      homepage: https://biopython.org/
      documentation: https://biopython.org/wiki/Documentation
      licence: ["BSD-3-Clause"]
      identifier: ""
input:
  - - pseudogenomes:
        type: file
        description: |
          Consensus FASTA files for each sample to be aligned
        pattern: "*.fa"
        ontologies: []
  - - ref_meta:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'reference' ]
    - fasta:
        type: file
        description: |
          Reference genome FASTA file to use as the basis for the MSA
        pattern: "*.{fa,fasta}"
        ontologies: []
output:
  aligned_pseudogenomes:
    - - "aligned_pseudogenomes.fas":
          type: file
          description: Multiple sequence alignment of pseudogenomes in FASTA format
          pattern: "*.fas"
          ontologies: []
  low_quality_metrics:
    - - "low_quality_pseudogenomes.tsv":
          type: file
          description: TSV file containing metrics for samples flagged as low quality
          pattern: "*.tsv"
          ontologies: []
  versions_alignpseudogenomes:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - python:
          type: string
          description: The tool name
      - "python --version | sed 's/Python //g'":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - python:
          type: string
          description: The tool name
      - "python --version | sed 's/Python //g'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@antunderwood"
maintainers:
  - "@avantonder"
